---
- hosts: dnsservers
  become: true
  vars:
    dns_domain: 0xd7.net
    dns_domain_reverse: 20.16.172.in-addr.arpa 
    dns_addins: files/dns/dns_addins
    dns_addins_reverse: files/dns/dns_addins_reverse
    dns_addins_reverse_dest: /var/named/172.16.20_addins.zone 
    dns_addins_dest: /var/named/0xd7_addins.zone
    dns_zonefile: /var/named/0xd7.zone
    dns_reversefile: /var/named/172.16.20.zone

  tasks:
  - name: Ensure "Include" statement is present in zone file
    lineinfile:
      path: "{{ dns_zonefile }}"
      line: "$INCLUDE {{ dns_addins_dest }}"
      insertafter: EOF
      backup: true
    notify: restart named

  - name: Ensure "Include" statement is present in reverse file
    lineinfile:
      path: "{{ dns_reversefile }}"
      line: "$INCLUDE {{ dns_addins_reverse_dest }}"
      insertafter: EOF
      backup: true
    notify: restart named

  - name: Ensure "DNS Addins" are present
    copy:
      src: "{{ dns_addins }}"
      dest: "{{ dns_addins_dest }}"
      owner: root
      group: named
      mode: '0644'
      backup: true

  - name: Ensure "DNS Addins" are present
    copy:
      src: "{{ dns_addins_reverse }}"
      dest: "{{ dns_addins_reverse_dest }}"
      owner: root
      group: named
      mode: '0644'
      backup: true

  handlers:
  - name: restart named
    service:
      name: named
      state: restarted
